spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root1234
    url: jdbc:mysql://localhost:3306/wallettrack?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show-sql: true